services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${PORT:-9000}
